### ISSUE TITLE
Problem with mapping of Primary Name

### ISSUE THREAD

**Issue by american-art-admin** [american-art/aac_mappings#22]
The variable ?type_label is undefined.

SELECT ?actor_name ?type_label ?actor_class
WHERE {
<http://data.americanartcollaborative.org/autry/maker/leighwilliamrobinson> a crm:E39_Actor ;
  crm:P131_is_identified_by ?actor_class .
?actor_class a crm:E82_Actor_Appellation ;
  rdf:value ?actor_name ;
  crm:P2_has_type <http://vocab.getty.edu/aat/300404670> .

}

```

**Comment by workergnome** [comment]
Good catch.  Fixed.
