### ISSUE TITLE
Question on mapping of Descriptions

### ISSUE THREAD

**Issue by VladimirAlexiev** [american-art/aac_mappings#27]
Do you actually have info on who wrote the descriptions? (Main and Other)
```ttl
  ?alt_description_class crm:P94i_was_created_by ?alt_desc_authorship_event .
  ?alt_desc_authorship_event a crm:E65_Creation ;
    crm:P14_carried_out_by ?alt_desc_author_class .
  ?alt_desc_author_class a crm:E39_Actor;
    rdfs:label ?alt_desc_author .
```

**Comment by workergnome** [comment]
I'm pretty sure I saw at least one institution claim to have this, so we added it—It's certainly optional, and I don't expect it to be common.

**Comment by azaroth42** [comment]
It's optional, and follows the standard patterns.  Propose close.

**Comment by VladimirAlexiev** [comment]
Please produce this example. 
Otherwise why not introduce such complications for every piece of data, because it might be present?
