### ISSUE TITLE
Question on mapping of Subject vs Concept

### ISSUE THREAD

**Issue by VladimirAlexiev** [american-art/aac_mappings#28]
[Subject](http://review.americanartcollaborative.org/entity/E22_Man-Made_Object#field_11-search_0) "What the work depicts" is mapped differently from [Concept](http://review.americanartcollaborative.org/entity/E22_Man-Made_Object#field_13-search_0) "What the work is about".

Can you give some examples of Subject vs Concept values?

`P62_depicts` is a shortcut of `P128_carries/P129_is_about`, which is correct only if the nature of aboutness is visual (eg a portrait of someone). If this cannot be ascertained, the long-path should be used in both cases.

**Comment by workergnome** [comment]
I think this is the distinction we're hoping to capture here.  Subject is "visually depicted", and "Concept" is conceptual aboutness.

**Comment by azaroth42** [comment]
The painting depicts Nelson (ulan:blablabla), and is about Military (aat:blablabla).

**Comment by VladimirAlexiev** [comment]
I can easily believe this is true for NPG (because those are Portraits).
But for other museums it may be false.

Nelson vs Military is correct: but can you give some links to specific data you've used to decide this mapping?
Or I'll just report on specific data if I find exceptions.

**Comment by workergnome** [comment]
I haven't looked at data for the institutions, just proposed a structure for distinguishing between these two types of aboutness.  Certainly if you find problems in the data where they're misclassified, call that out!
