### ISSUE TITLE
Problem with mapping of Object ID

### ISSUE THREAD

**Issue by raviraju** [american-art/aac_mappings#3]
I expected to see:

E42_Identifier to have property(rdf:value) set to an <identifier>

but instead I saw:

E42_Identifier to has both property (rdf:value and rdfs:label) set to an <identifier>

Query has rdfs:value instead of rdf:value
 ?identifier_url a crm:E42_Identifier ;
  rdfs:value ?identifier ;
  crm:P2_has_type <http://vocab.getty.edu/aat/300404621> .

**Comment by azaroth42** [comment]
The reason to have both is that every resource should have a label.  The label of the identifier can be just the identifier string itself... which is also the value of the identifier.  Hence both rdf:value and rdfs:label.

Agree that rdfs:value is a typo to fix

**Comment by workergnome** [comment]
Fixed the `rdfs:value` typo.
