### ISSUE TITLE
Cannot view queries at http://review.americanartcollaborative.org/

### ISSUE THREAD

**Issue by raviraju** [american-art/aac_mappings#32]
All of sparql queries are reporting : Nothing to see here...

**Comment by workergnome** [comment]
I'm seeing this, too...I haven't changed anything, I don't think—can you check if the sparql endpoint is still working?

**Comment by workergnome** [comment]
Any idea what's going on here?  It's still working for other endpoints, so I think it's likely something with the AAC sparql.

**Comment by VladimirAlexiev** [comment]
Probably the SPARQL endpoint. Right now it shows stuff for me

**Comment by workergnome** [comment]
Agreed.  Think it was just down at that moment.
