### ISSUE TITLE
mapping of Bibliographic Reference

### ISSUE THREAD

**Issue by VladimirAlexiev** [american-art/aac_mappings#39]
Where is the mapping for Bibliographic Reference? I can't see it, I see only Catalogue Raisonné.

I think the mapping of both should be:
```
<object> is documented in <reference>, <CatalogueRaisonné>.
<reference> a Document; rdf:label "description"; 
  has_type aat:300311954. # reference (référence bibliographique)
<CatalogueRaisonné>a Document; rdf:label "description";
  has_type aat:300026061. # Catalogue Raisonné
```
Document is more appropriate than Linguistic Object (which means a piece of text): surely catalogs also have pictures.

https://github.com/american-art/cbm/issues/52 says to use 300026497 bibliographies "Lists of books, documents, and other bibliographical items". But this concept is wrong for this purpose: that piece of data describes a single document, not a List.
The right concept is 300311954 reference (référence bibliographique) (that is a `<document by function>`)

**Comment by VladimirAlexiev** [comment]
Now I see that CBM have actually lumped a bunch of docs in one field, eg for object/20 it is (bullets added for clarity):
- Augustus Thorndike Perkins, A Sketch of the Life and a List of Some of the Works of John Singleton Copley (Boston: James R. Osgood and Company, 1873), p. 99 // 
- F. W. Bayley, Life and Works of John Singleton Copley Founded on the Work of Augustus Thorndike Perkins (Boston: Taylor Press, 1915), pp. 208-209 (as Mr. Rogers of Salem) //
- J.B.P., "A Copley Portrait," Museum of Fine Arts Bulletin, February 1917, p. 5, illustrated //
- Theodore Bolton and H. L. Binsse, "John Singleton Copley: Appraised as an Artist in Relation to His Contemporaries," Antiquarian, December 1930, p. 118 //
- B. N. Parker and A. B. Wheeler, John Singleton Copley: American Portraits in Oil, Pastel and Miniature (Boston: Museum of Fine Arts, 1938), pp. 162-163, illustrated pl. 76 //
- Jules David Prown, John Singleton Copley In America, 1738 - 1774 (Cambridge, MA: Harvard University Press, 1966), p. 226; illustrated fig. 217 //
- American Paintings in the Museum of Fine Arts, Boston (Boston: Museum of Fine Arts, 1969), no. 274, vol. I, p. 68, vol. II, illustrated fig. 57

My oh my, I'm certain in their system they edit them separately, so why did they lump them in one CSV field? Is it feasible for ISI to split this by `//`?
If not, then 300026497 bibliographies is correct, but that's a terrible way to emit this data.
(We may just as well lump all the info in one big P3_has_note ;-))

**Comment by workergnome** [comment]
We sat down, drew a giant diagram of what it would take to specifically model individual citations using CIDOC-CRM and/or FRBROO, and at the end decided that this was probably out of the scope of what could be reasonably accommodated in the AAC process.  Instead, we're treating the bibliography and/or catalog raisonnés as opaque text blocks.  Certainly not optimal, but the best we can do at this point.

**Comment by azaroth42** [comment]
The data isn't granular enough to parse out the citations (I think as you see with CBM) and Karma isn't the tool to be writing text parsers in. So yes, terrible, but the only other option is to drop it completely at the moment :(

**Comment by VladimirAlexiev** [comment]
Splitting on `//` can hardly be called "writing parsers". 
Do the other museums follow the same pattern?
