### ISSUE TITLE
Distinction bw Preferred ID and Object ID

### ISSUE THREAD

**Issue by raviraju** [american-art/aac_mappings#4]
Please cite some examples from any museum data, so as to distinguish these fields.

**Comment by azaroth42** [comment]
I think the preference is from institutional policies, and thus not in the data.  Some will prefer the accession number, others a database record number, and I'm certain there'll be other types.

@edgartdata @kateblanch is this recorded somewhere already, or can we poll the museums for their preferences?

**Comment by edgartdata** [comment]
It is not recorded in the data files provided by the museums. It would be better to poll them quickly. The Data WG can do that.

**Comment by kateblanch** [comment]
I will need to ask partners who among them uses the preferred ID field...otherwise it will take me hours upon hours to dig through each data set for each partner. Stay tuned.

**Comment by kateblanch** [comment]
I've proposed this to partners:
Object ID – will be mapped to optional field Object ID
Object Number – will be mapped to mandatory field Preferred ID

For partners who do not have a field named "Object Number", they will tell us which field to map to Preferred ID. I will post responses here as they come in, not sure how else to compile them? Open to ideas.

**Comment by kateblanch** [comment]
AAA:
CollectionID and ItemID should map to the mandatory PreferredID.
Collcode should map to ObjectID.  The collcode is only in the Collection.xls.  Item.xls does not have any data to map to the optional ObjectID.

**Comment by kateblanch** [comment]
CCMA:
"Disp_Access_No" is the preferred ID for Colby's objects and "embark_ID" is the object's ObjectID. Though is it a problem that the accession number can change? Our registrars flip the accession number when the object changes ownership status. 

Does anyone have feedback for Charlie about changing accession numbers being used for PreferredID?

**Comment by cbutcosk** [comment]
Yeah, I can see both ways--the DB key and the accession number each express identity in their own way. Another question that I think will help clarify the ins/outs of this for me, is the preferred ID ultimately going to be part of the URI that represents that object (i.e., <http://data.aac.org/ccma/object/1425> versus <http://data.aac.org/ccma/object/1994.21.4A>)?

**Comment by ddegler** [comment]
@cbutcosk The preferred ID will be part of the unique LOD identity. That is why both accession number and DB key are problematic, but what we have to work with. Accession number changes inside institutions for various reasons, but hopefully rarely when actual ownership (+ responsibility?) changes. DB key can change when systems are changed (a more likely occurrence?), although the old key can be carried forward (but at some risk of disuse, and divergence with new keys).

Fortunately, a SameAs link can be established to a new ID when something changes, even though it can introduce some confusion among outside users. Traditional internal data systems are not yet geared toward their responsibilities to open, persistent use by external parties. In the meantime, I suggest selecting the most stable ID. But I also defer to others who may have a better view of norms from other institutions (e.g. @azaroth42 from libraries, or @caknoblock from other non-CH data sources).

**Comment by kateblanch** [comment]
Our ObjectID (as opposed to PreferredID/AccessionNumber) is actually more stable and I think more appropriate for use in the URL (to @cbutcosk's question - which one is used in the URL). I wish I would have thought of that earlier!

I could quickly poll the AAC data owners and see which they had imagined would be part of URL? Not sure if that is helpful...or on time, but happy to get more info - let me know.

**Comment by kateblanch** [comment]
ACM: 
Our Accession Number field is our PreferredID.

**Comment by cbutcosk** [comment]
I'd prefer Colby's LOD structure follow whatever is used across the AAC, so it sounds like we'll use the accession num as the prefID and create some sameAs links for changed accession nums.

**Comment by workergnome** [comment]
I'm going to close this, since it seems resolved at this point.  Feel free to re-open if needed.
