### ISSUE TITLE
Replace Actor Appellation with Appellation in v1.1

### ISSUE THREAD

**Issue by azaroth42** [american-art/aac_mappings#41]
Per http://www.cidoc-crm.org/sites/default/files/minutes%20of%2037th%20meeting%20Berlin%20%28draft%29.pdf
 page 12, the SIG has decided to delete E82 Actor Appellation.

We should thus just use a regular Appellation when we need to model the name of a resource as a resource in its own right.

**Comment by workergnome** [comment]
Flagged and tagged.

Wonder what it would take to get the CRM to use semantic versioning.

**Comment by workergnome** [comment]
This has been adopted in the Linked.Art spec.
