### ISSUE TITLE
Exhibition mapping is missing

### ISSUE THREAD

**Issue by VladimirAlexiev** [american-art/aac_mappings#43]
There's only a mapping of Event including only Title. But:
- you at least need to indicate P2, to distinguish this event from others (eg Production): https://github.com/american-art/npg/issues/5
`crm:P2_has_type aat:300054766; # exhibition (event)`
- CBM (at least) has structured info, incl for Traveling Exhibitions: https://github.com/american-art/cbm/issues/19, including shared exhibitions (object-exhibition is n-n), venues (sub-exhibitions), dates of main and sub-exhibition, and sub-exhibition organizer (venue constituent)
- In https://github.com/american-art/PUAM/issues/8#issuecomment-236846740 I proposed a mapping for Traveling Exhibitions

**Comment by workergnome** [comment]
Yeah—Craig said that given the constraints, they weren't going to map exhibitions or bibliographies, so we didn't bother writing out target models for them.  Disappointing, but that's how it worked out.

**Comment by azaroth42** [comment]
:+1:  Something to do in 1.1. We discussed / whiteboarded a bunch of ideas towards this, but need to revisit with better understanding of the available data, rather than the perfect world.

**Comment by VladimirAlexiev** [comment]
https://github.com/american-art/cbm/issues/19#issuecomment-275395612 confirms that CBM has structured data.
So AAC took structured data and converted it to "linked strings". Disappointing.

**Comment by workergnome** [comment]
Agreed.  Unfortunately, it's not in our hands, and the decision was made to optimize for the maximum number of institutions, even if that means that all the data available doesn't get mapped.

**Comment by objectid459** [comment]
We hope a new grant will cover mapping what we can't now and also be an opportunity to update the target model.Eleanor -----Original Message-----

**Comment by VladimirAlexiev** [comment]
- CRM is flexible enough to capture structured data when present, and have a "minimum common denominator" (i.e. strings) as fallback and when structured data is not available.
- at least add this:
`crm:P2_has_type aat:300054766; # exhibition (event)`
 You don't plan on **lack of RDFS reasoning** to distinguish between Exhibition and Production, correct?

**Comment by azaroth42** [comment]
> Craig said that given the constraints, they weren't going to map exhibitions or bibliographies, so we didn't bother writing out target models for them

> Something to do in 1.1.

⬆️
