### ISSUE TITLE
Problem with mapping of Artist / Object 9895 

### ISSUE THREAD

**Issue by kateblanch** [american-art/aac_mappings#44]
--Update, tested this for Object 34753 too which has an individual artist and the same problem persists (not specific to institutions as the example cites below).

Our constituents file is split into 6 subfiles...not sure why this is but I think it's preventing the validator from reading our artists names. 

I expected to see:

*Artist name "Tiffany and Company"* -- Note there is a separate model for institution/individual/culture in our data (I can understand why but this freaks me out).

but instead I saw:

*Nothing/Blank*

The current query was:

```ttl
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX crm: <http://www.cidoc-crm.org/cidoc-crm/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX schema: <http://schema.org/>

SELECT ?actor_name ?actor_type ?actor_class
WHERE {
<http://data.thewalters.org/object/9895> a crm:E22_Man-Made_Object ;
   crm:P108i_was_produced_by ?production_event .

?production_event a crm:E12_Production ;
  crm:P14_carried_out_by ?actor_class .

OPTIONAL {
  ?actor_class a ?actor_type .
}
OPTIONAL {
  ?actor_class rdfs:label ?actor_name.
}

}


```

**Comment by workergnome** [comment]
Yup—this is a valid issue.  The production (http://data.americanartcollaborative.org/page/wam/object/9895/production) does not have any Actors associated with it.

**Comment by bsnikhila** [comment]
Fixed it
