### ISSUE TITLE
query for Actor Other Names

### ISSUE THREAD

**Issue by VladimirAlexiev** [american-art/aac_mappings#49]
The query for [Actor Other Names](http://review.americanartcollaborative.org/entity/E39_Actor#field_7-search_0) is not selective enough and also returns Primary names.
Check with http://data.crystalbridges.org/person-institution/73

**Comment by VladimirAlexiev** [comment]
@workergnome we dont have a separate repo for http://review.americanartcollaborative.org or the queries, right?

**Comment by workergnome** [comment]
Technically, **this** is the repository for review.americanartcollaborative.org.  I'll work on this.

**Comment by VladimirAlexiev** [comment]
Then you need to post bugs against museums who have implemented the current mapping.
