### ISSUE TITLE
why use rdf:value?

### ISSUE THREAD

**Issue by VladimirAlexiev** [american-art/aac_mappings#5]
@workergnome @azaroth42
http://review.americanartcollaborative.org/entity/E39_Actor:
Why use `rdf:value`? CRM doesn't specify the use of this property, and I don't  know any provider who uses it.
Use `crm:P3_has_note` (as per CRM spec) or `rdfs:label` (also sort of accepted by CRM SIG)

**Comment by azaroth42** [comment]
We're intentionally avoiding P3 as semantically meaningless.  CRM scope notes redefine its meaning based on the subject of the triple, which is not allowed in RDF.  Sometimes it's a note, sometimes a value, sometimes a description, sometimes a transcription. Instead, we use rdf:value consistently as the value/representation of the resource, as intended.  We already (obviously) use the ontology (e.g. rdf:type!) so there's no new ontology dependencies.

Propose close wontfix.

**Comment by VladimirAlexiev** [comment]
I disagree. P3 is the value of a title, the value of a transcribed title, the human-readable value of a Time-Span (as opposed to P82a/b which are machine-readable dates, without nuance and usually a wider interval).
Please prove your claims quoting from CRM scope notes.

As I say above, you'll be the first in the world to use rdf:value with CRM. And where else is it used, with some DC Qualified data?
At least rdfs:label has been used with CRM, and many semantic systems display it as label of a node, in lieu of the URL.

**Comment by azaroth42** [comment]
E33: The __text__ of an instance of E33 Linguistic Object can be documented in a note by P3 has note: E62 String

E34: The __transcription__ of the text can be documented in a note by P3 has note: E62 String.

E90: The property P3 has note allows for the __description__ of this content model.

P46: Overall __descriptions__ of the structure of an instance of E18 Physical Thing are captured by the P3 has note property.

Indeed the scope notes for P3 say:  the CRM formalism is not regarded as sufficient to express everything that can be said.

So we SHOULD use rdf:value when it's a value, and dc:description when it's a description.

**Comment by VladimirAlexiev** [comment]
It's true that P3 is sometimes used for general notes. eg the P46/E48 example that you give.

But in Titles, Appellations and Linguistic Objects, P3 is the value. Eg in the rest of your examples:
- E33: this is the value of the Linguistic Object
- E34: the text of the Inscription is not the inscription, but is the closest you can render it in some script; and you can call it the "textual value" of the inscription
- E90: "may completely be represented by a serialized digital content model... P3 has note allows for the description of this content model": the word "description" is incorrectly used, in this case it's clear that P3 carries this digital content, so it's the value. (Though I would kill the idiot to put a TIFF image blob in P3_has_note)

What would you put in rdfs:label of a Title/Appellation? Or leave it without one?

**Comment by azaroth42** [comment]
It cannot be more than one thing at once. 

Propose close.

**Comment by VladimirAlexiev** [comment]
> difference of opinion as to best practices

Inventing a new thing is rarely best practice, imho.
