### ISSUE TITLE
Location mapping is  poor

### ISSUE THREAD

**Issue by VladimirAlexiev** [american-art/aac_mappings#58]
See [production location mapping](http://review.americanartcollaborative.org/entity/E22_Man-Made_Object#field_5-search_0). 
For the place it specifies a label and geo coordinates (split in two nodes, which is very strange).

Consider eg https://github.com/american-art/PUAM/issues/49. PUAM places have:
- structured name, also indicating a place hierarchy: Continent, SubContinent, Country, Region, State, City, County, SubRegion, Locale, Locus, River, Excavation. The best is to make these out as separate nodes and interconnect them
- geonames link (some of them)

**Comment by workergnome** [comment]
As I stated in my comment on https://github.com/american-art/PUAM/issues/49, I think that construction of the full location hierarchy is probably out of scope for this—gazetteers are a complicated beast, and I think the effort would be better spent in linking to external authorities if that level of precision is needed.

**Comment by VladimirAlexiev** [comment]
Agree. That's for the future
