### ISSUE TITLE
Problem with mapping of Current Owner

### ISSUE THREAD

**Issue by KatherineMoloney** [american-art/aac_mappings#66]
I expected to see:

*Amon Carter Museum of American Art*

but instead I saw:

blank

The current query was:

```ttl
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX crm: <http://www.cidoc-crm.org/cidoc-crm/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX schema: <http://schema.org/>

SELECT ?owner_name ?owner_class
WHERE {
<http://data.americanartcollaborative.org/acm/object/10_1967_474> a crm:E22_Man-Made_Object ;
   crm:P52_has_current_owner ?owner_class .
OPTIONAL {
  ?owner_class a crm:E40_Legal_Body ;
    rdfs:label ?owner_name .
}
  

}


```

**Comment by kateblanch** [comment]
Hi David (@workergnome)! This issue prompted me to test all the partners'  crm:P52_has_current_owner value, and I will email you and Duane separately about a couple non-urgent questions. 

The mapping is present for crm:P52_has_current_owner + E40:LegalBody but no value exists. I know that this value is NOT in the partners' data sets so was it a default value that gets coded into the data?

**Comment by workergnome** [comment]
This has been moved to the correct repo.
