### ISSUE TITLE
Problem with mapping of Creation Date

### ISSUE THREAD

**Issue by cbutcosk** [american-art/aac_mappings#76]
I expected to see:

On the Browse app I expected "Display Date" to be a string (eg, for http://data.americanartcollaborative.org/ccma/object/1157 I expect "19th Century" as the display label). 

but instead I saw:

The xsd:date for the production's beginning and end as strings (eg, "1800-01-01 to 1899-12-31"). The data coming out of the AAC triplestore (and in the review tool) looks right, though. The CCMA pages may just need re-compiled from fresh data?

The current query was:

```ttl
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX crm: <http://www.cidoc-crm.org/cidoc-crm/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX schema: <http://schema.org/>

SELECT ?display_date ?earliest_date ?latest_date ?production_event
WHERE {
<http://data.americanartcollaborative.org/ccma/object/1157> a crm:E22_Man-Made_Object.
{
  <http://data.americanartcollaborative.org/ccma/object/1157> crm:P108i_was_produced_by ?production_event .
} UNION {
  ?production_event crm:P108_has_produced <http://data.americanartcollaborative.org/ccma/object/1157> .
} UNION {
  <http://data.americanartcollaborative.org/ccma/object/1157> crm:P108i_was_produced_by ?intermediate_event .
  ?intermediate_event crm:P9_consists_of ?production_event .
}
?production_event a crm:E12_Production ;
  crm:P4_has_time-span ?production_timespan. 
?production_timespan a crm:E52_Time-Span.
OPTIONAL {
  {
   ?production_timespan crm:P82a_begin_of_the_begin ?earliest_date.
   ?production_timespan crm:P82b_end_of_the_end ?latest_date.
  } UNION {
    ?production_timespan crm:P82_at_some_time_within ?earliest_date.
    ?production_timespan crm:P82_at_some_time_within ?latest_date.
  }
}
OPTIONAL {
  {
    ?production_timespan crm:P3_has_note ?display_date. 
  } UNION {
    ?production_timespan skos:prefLabel ?display_date. 
  } UNION {
    ?production_timespan rdfs:label ?display_date. 
  }
}

}


```

**Comment by VladimirAlexiev** [comment]
@workergnome this part of the query is wrong:
```
    ?production_timespan crm:P82_at_some_time_within ?earliest_date.
    ?production_timespan crm:P82_at_some_time_within ?latest_date.
```
because it can pick the same date twice (nothing says `?earliest_date<?latest_date` but it's not so easy to add that because there may be just one, and `<` would work only with property formatted `xsd:date`)

**Comment by cbutcosk** [comment]
FWIW (separately from query correctness) the problem I raised this for--the dates showing up funky in the browse app--was fixed in the most recent browse app version.

**Comment by workergnome** [comment]
Because the interface is expecting `crm:P82a_begin_of_the_begin` and `crm:P82b_end_of_the_end`, if there's a single date in `cam:P82_at_some_time_within`, I _believe_ it's appropriate to consider that date to be both the beginning and the end of that time period.

Would be happy to discuss date logic at length, though!

**Comment by VladimirAlexiev** [comment]
@workergnome http://review.americanartcollaborative.org/entity/E22_Man-Made_Object#field_4-search_0 doesn't specify P82, so we could make any number of guesses what people may put in P82.
However, both P82a and P82b are subprops of P82, so we could expect two different dates.

**Comment by workergnome** [comment]
Agreed.  @VladimirAlexiev, happy to talk about this, but any objection to closing this issue?

**Comment by VladimirAlexiev** [comment]
@cbutcosk Could you retest and if the issue still stands, recreate it in the CCMA project? Then close this one.

**Comment by cbutcosk** [comment]
👍
